#!/usr/bin/python3

import sys
import math
from timeit import default_timer as timer

def factorize(n):
    if n < 2:
        return

    # Optimized trial division
    limit = int(math.sqrt(n)) + 1
    for i in range(2, limit):
        if n % i == 0:
            return n//i, i
    return n, 1 # prime

if __name__ == '__main__':

    start = timer()
    limit = start + 5 # 5 second limit

    try:
        filename = sys.argv[1]
        with open(filename) as f:
            lines = (line.strip() for line in f)
            nums = map(int, lines)

            for n in nums:
                if timer() >= limit:
                    print('Time limit reached')
                    break

                result = factorize(n)
                print(f'{n}={result[0]}*{result[1]}')

    except IndexError:
        print('Usage: factors <file>')
