#!/usr/bin/python3

import math
from timeit import default_timer as timer

def pollard_p_1(n):
    a = 2
    cycle_len = 2
    start = timer()

    while timer() - start < 5:
        a = pow(a, cycle_len, n)
        factor = math.gcd(a - 1, n)

        if factor > 1 and factor < n:
            return factor

        cycle_len += 1

    return None

if __name__ == '__main__':

    n = # read large RSA number
    factor = pollard_p_1(n)

    if factor:
        print(f'{n} = {factor} * {n//factor}')
    else:
        print('No factor found in time limit')
